import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from './providers';
import { Toaster } from 'sonner'


const geistSans = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased p-4 md:p-6 lg:p-8`}
        >
          <Toaster position="top-center"/>
          <StoreProvider>
            {children}
          </StoreProvider>
        </body>
    </html>
  );
}
